### ISSUE TITLE
MODEL_FILE_PATH is not defined

### ISSUE THREAD

**Issue by shin-imai** [AIWintermuteAI/DeepSpeech_RaspberryPi4_Hotword#4]
Hi, I am testing your articles on raspberry pi 4 with 8GB ram.

 I followed the instruction but I get the following error. 

```
# python3 mic_streaming.py --keywords blueberry
Traceback (most recent call last):
  File "mic_streaming.py", line 270, in <module>
    main()
  File "mic_streaming.py", line 224, in main
    parser.add_argument('--model_file_path', help='absolute path to model parameter file', default=MODEL_FILE_PATH)
NameError: name 'MODEL_FILE_PATH' is not defined
```

I tried to fix but I got other errors. Can you help?

**Comment by AIWintermuteAI** [comment]
Hi! This is because I didn't put specific version of pvpporcupine in install.sh script and they have made some breaking changes in API in 1.8.7 version. I already updated the script to latest version of pvpporcupine and DeepsSpeech, feel free to test it and see if that resolved the problem.

**Comment by AIWintermuteAI** [comment]
Hoping that recent update resolved the issue for you.
