### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by pi-pi-pi** [AIWintermuteAI/DeepSpeech_RaspberryPi4_Hotword#5]
Thanks for your work on this to make it easier to implement these tools. I am getting an error and not sure where to even start.

There is not a lot of information present with this error:

pi@pivoice:~/speech $ sudo python3 mic_streaming.py --keywords blueberry
Initializing model...
INFO:root:Model: /home/pi/speech/deepspeech-0.9.1-models.tflite
TensorFlow: v2.3.0-6-g23ad988
DeepSpeech: v0.9.3-0-gf2e9c85
Illegal instruction

Any guideance?

Just FYI, I had to run this command as well following your script:
`sudo apt-get install libsndfile1`

Thanks.

**Comment by AIWintermuteAI** [comment]
It looks like you're trying to run it on an unsupported platform. My guess would be that you're running it on an old(-ish) PC? The error is very similar to these
https://github.com/tensorflow/tensorflow/issues/17411#issuecomment-373938846

**Comment by pi-pi-pi** [comment]
Doh. Pretty sure you are correct. Trying a better machine now. Thanks!
