### ISSUE TITLE
DeepSpeech

### ISSUE THREAD

**Issue by silahsor** [AIWintermuteAI/DeepSpeech_RaspberryPi4_Hotword#6]
Hii,
Could ı ask some questions about Mozilla DeepSpeech? Firslty my english is not so good please forgive me :)
1-)I implemented all codes and they work well.On the other hand,when speech to text,it can not translate my all sentence,it just understand some words.How can ı solve this problem?
2-)I want to work on Turkish language,I search it how can ı do that? but ı did not understand actually :(
3-)I want to change hotword,how can ı change?

If you help me,I will be so happy :) Thank you sir

Best regards

**Comment by AIWintermuteAI** [comment]
Hello, 
I am not a developer of DeepSpeech, this questions are better to be addressed on their GitHub or forum :)
+ FIY Active development of DeepSpeech has moved to https://github.com/coqui-ai/STT
